services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sql_server_dev
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
    volumes:
      - /home/ivan/Repos/CatalogETL/docker/backups/KITSProduct_20260401_1055PM.bak:/var/opt/mssql/backup/KITSProduct_20260401_1055PM.bak

  db:
    image: pgvector/pgvector:pg17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"

  pgapi:
    build:
      context: ../pg-api
      dockerfile: Dockerfile
    container_name: pgapi_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mysecretpassword@db:5432/productdb
    ports:
      - "8000:8000"

  webapp:
    build:
      context: ../apps/web-app
      dockerfile: Dockerfile
    container_name: webapp_service
    restart: always
    volumes:
      - ../apps/web-app:/usr/share/nginx/html
    ports:
      - "80:80"